services:
  task-ui:
    build:
      context: ./task-ui
    container_name: task-ui
    ports:
      - "4200:4200"
    volumes:
      - ./task-ui/:/usr/src/app

  server:
    build:
      context: ./task-server
    container_name: task-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: task
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: example
    depends_on:
      - mongo
    networks:
      - task-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: task
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - task-network

networks:
  task-network:
    driver: bridge
